# Generated by Django 2.2.16 on 2021-04-07 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercostfunctions',
            name='element_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waterproof_intake.ElementSystem'),
        ),
        migrations.AddField(
            model_name='usercostfunctions',
            name='intake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waterproof_intake.Intake'),
        ),
    ]
